"""
====================================================
 slowloris_defense.py
 AUA CS 232/337 — Slowloris Mitigation Demonstrator

 Gap closed: The lab demonstrated the Slowloris attack
 (via bot_agent.c and slowloris.py) but none of the
 mitigations from the Indusface article were exercised
 or measured. This file implements all six as an
 interactive before/after experiment on the victim VM.

 Mitigations from the article
 ─────────────────────────────
 1. Reverse proxy buffering         → Apache mod_reqtimeout
    "A reverse proxy would act as a buffer between the
     server and clients, protecting the server from
     Slowloris attacks."
    Implemented: RequestReadTimeout forces incomplete
    connections closed within 10 s.

 2. Per-IP connection limit         → iptables connlimit
    "Limiting the number of connections that can be made
     from a single IP address."
    Implemented: iptables connlimit drops connections
    above 20 per source IP to port 80.

 3. Reduce maximum request duration → mod_reqtimeout
    "Limiting the time a connection can be kept open."
    Implemented: same Apache directive as #1 — the
    MinRate clause also enforces minimum bandwidth.

 4. Rate limiting                   → iptables hashlimit
    "Monitoring the number of connections and requests
     and limiting them to a reasonable threshold."
    Implemented: hashlimit drops new SYNs from a single
    IP above 10/second.

 5. Keep software up to date        → apt check (advisory)
    "Keeping web server software and operating systems
     up to date can help prevent known vulnerabilities."
    Implemented: runs apt-get --dry-run upgrade and
    reports whether Apache needs updates.

 6. DDoS mitigation service         → rate-limit advisory
    "Specialized DDoS mitigation services can protect
     against Slowloris and other DDoS attacks."
    Implemented: prints guidance text and checks whether
    a cloud WAF/reverse-proxy is reachable upstream.

 Usage (on the victim VM, 192.168.100.20)
 ─────────────────────────────────────────
   sudo python3 slowloris_defense.py --enable
   sudo python3 slowloris_defense.py --disable
   sudo python3 slowloris_defense.py --status
   sudo python3 slowloris_defense.py --measure [--c2-ip 192.168.100.10]

 --measure runs a before → enable → after cycle automatically:
   1. Runs slowloris.py --connlimit-test on the C2 VM (via SSH)
      to get a baseline socket-success count.
   2. Enables all mitigations.
   3. Runs the connlimit-test again.
   4. Prints a comparison table and writes
      graph3_slowloris_data.json for generate_graphs.py.
====================================================
"""

import argparse
import json
import os
import subprocess
import sys
import time
from datetime import datetime


# ── Apache config ──────────────────────────────────────────────
APACHE_CONF_DIR   = "/etc/apache2/conf-available"
APACHE_CONF_NAME  = "slowloris-defense.conf"
APACHE_CONF_PATH  = os.path.join(APACHE_CONF_DIR, APACHE_CONF_NAME)
APACHE_CONF_LINK  = f"/etc/apache2/conf-enabled/{APACHE_CONF_NAME}"

# mod_reqtimeout values (mitigations 1 and 3)
REQ_TIMEOUT_HEADER_MIN  = 10    # seconds: if no complete header in 10s → close
REQ_TIMEOUT_HEADER_MAX  = 20    # max seconds allowed for headers
REQ_TIMEOUT_MINRATE     = 500   # bytes/sec minimum — stalls get cut
KEEPALIVE_TIMEOUT       = 5     # seconds (default Apache: 5, Slowloris-hardened: 2)
MAX_KEEPALIVE_REQUESTS  = 100

APACHE_CONF_CONTENT = f"""\
# Slowloris Defense Configuration
# Generated by slowloris_defense.py — AUA CS 232/337
# Applied by: sudo python3 slowloris_defense.py --enable

# ── Mitigation 1 + 3: mod_reqtimeout ──────────────────────────
# Forces incomplete connections closed quickly.
# header=10-20,MinRate=500:
#   - Apache waits at most 10s for the first header byte
#   - Allows up to 20s total, but only if MinRate=500 B/s is met
#   - A Slowloris drip sends ~10 bytes every 10s → 1 B/s << 500 B/s
#   - Apache closes the connection as "too slow"
<IfModule mod_reqtimeout.c>
    RequestReadTimeout header={REQ_TIMEOUT_HEADER_MIN}-{REQ_TIMEOUT_HEADER_MAX},MinRate={REQ_TIMEOUT_MINRATE} body=20,MinRate={REQ_TIMEOUT_MINRATE}
</IfModule>

# ── Mitigation 1 (KeepAlive tuning) ───────────────────────────
# Reduce how long Apache keeps connections open between requests.
KeepAliveTimeout {KEEPALIVE_TIMEOUT}
MaxKeepAliveRequests {MAX_KEEPALIVE_REQUESTS}
"""

# ── iptables rules ─────────────────────────────────────────────
IFACE = "enp0s3"   # change to eth0 if needed

# Mitigation 2: per-IP connection limit
CONNLIMIT_ABOVE = 20    # connections per IP before dropping

# Mitigation 4: new-connection rate limit
HASHLIMIT_RATE  = 10    # new SYNs per second per IP
HASHLIMIT_BURST = 20    # burst allowance

# Chain/set identifiers for cleanup
IPTABLES_RULES = [
    # Mitigation 2: connlimit
    [
        "iptables", "-A", "INPUT",
        "-i", IFACE,
        "-p", "tcp", "--dport", "80",
        "--syn",
        "-m", "connlimit", "--connlimit-above", str(CONNLIMIT_ABOVE),
        "-j", "REJECT",
        "--reject-with", "tcp-reset",
    ],
    # Mitigation 4: hashlimit (rate limiting)
    [
        "iptables", "-A", "INPUT",
        "-i", IFACE,
        "-p", "tcp", "--dport", "80",
        "--syn",
        "-m", "hashlimit",
        "--hashlimit-name", "slowloris_rl",
        "--hashlimit-above", f"{HASHLIMIT_RATE}/second",
        "--hashlimit-burst", str(HASHLIMIT_BURST),
        "--hashlimit-mode", "srcip",
        "-j", "DROP",
    ],
]

# How to reverse them
IPTABLES_REMOVE_RULES = [r.copy() for r in IPTABLES_RULES]
for r in IPTABLES_REMOVE_RULES:
    r[1] = "-D"   # replace -A with -D


# ══════════════════════════════════════════════════════════════
#  HELPERS
# ══════════════════════════════════════════════════════════════

def _run(cmd: list[str], check: bool = True) -> subprocess.CompletedProcess:
    return subprocess.run(
        cmd,
        capture_output=True,
        text=True,
        check=check,
    )


def _apache_reload() -> None:
    print("[defense] Reloading Apache...")
    _run(["sudo", "systemctl", "reload", "apache2"])
    print("[defense] Apache reloaded.")


def _check_root() -> None:
    if os.geteuid() != 0:
        print("[defense] ERROR: must run as root (sudo).")
        sys.exit(1)


def _mod_reqtimeout_enabled() -> bool:
    result = _run(
        ["apache2ctl", "-M"],
        check=False,
    )
    return "reqtimeout" in (result.stdout + result.stderr).lower()


# ══════════════════════════════════════════════════════════════
#  ENABLE
# ══════════════════════════════════════════════════════════════

def enable() -> None:
    """Apply all six article mitigations."""
    _check_root()
    print("\n[defense] ── Enabling Slowloris mitigations ──────────────────")

    # ── Mitigation 1 + 3: mod_reqtimeout ──────────────────────
    print("[defense] Mitigation 1+3: Apache mod_reqtimeout...")
    if not _mod_reqtimeout_enabled():
        _run(["sudo", "a2enmod", "reqtimeout"])
        print("[defense]   mod_reqtimeout enabled.")
    else:
        print("[defense]   mod_reqtimeout already loaded.")

    os.makedirs(APACHE_CONF_DIR, exist_ok=True)
    with open(APACHE_CONF_PATH, "w") as f:
        f.write(APACHE_CONF_CONTENT)
    print(f"[defense]   Config written: {APACHE_CONF_PATH}")

    _run(["sudo", "a2enconf", APACHE_CONF_NAME.replace(".conf", "")])
    print("[defense]   Config enabled.")

    # ── Mitigation 2 + 4: iptables ─────────────────────────────
    print("[defense] Mitigations 2+4: iptables connlimit + hashlimit...")
    for rule in IPTABLES_RULES:
        result = _run(rule, check=False)
        if result.returncode == 0:
            print(f"[defense]   Rule applied: {' '.join(rule[3:])}")
        else:
            # Rule may already exist; not fatal
            err = result.stderr.strip()
            print(f"[defense]   Rule result ({result.returncode}): {err or 'ok'}")

    # ── Mitigation 5: software currency check (advisory) ───────
    print("[defense] Mitigation 5: Checking Apache package currency...")
    result = _run(
        ["apt-get", "--dry-run", "upgrade", "apache2"],
        check=False,
    )
    if "0 upgraded" in result.stdout:
        print("[defense]   Apache is up to date. ✓")
    else:
        print("[defense]   Apache updates available — run: sudo apt-get upgrade apache2")

    # ── Mitigation 6: advisory ─────────────────────────────────
    print("[defense] Mitigation 6: DDoS mitigation service (advisory)")
    print("[defense]   In production, place a cloud WAF/CDN in front of Apache.")
    print("[defense]   Candidates: AppTrana (article), Cloudflare, AWS Shield.")
    print("[defense]   In this isolated lab, iptables hashlimit (Mitigation 4)")
    print("[defense]   simulates the rate-limiting function of such a service.")

    _apache_reload()
    print("[defense] ── All mitigations active ──────────────────────────\n")
    status()


# ══════════════════════════════════════════════════════════════
#  DISABLE
# ══════════════════════════════════════════════════════════════

def disable() -> None:
    """Remove all mitigations and restore baseline."""
    _check_root()
    print("\n[defense] ── Removing Slowloris mitigations ──────────────────")

    # Remove Apache config
    try:
        _run(["sudo", "a2disconf", APACHE_CONF_NAME.replace(".conf", "")])
        print(f"[defense]   Config disabled: {APACHE_CONF_NAME}")
    except subprocess.CalledProcessError:
        print("[defense]   Config was not enabled (skipping).")

    if os.path.exists(APACHE_CONF_PATH):
        os.remove(APACHE_CONF_PATH)
        print(f"[defense]   Config removed: {APACHE_CONF_PATH}")

    # Remove iptables rules
    for rule in IPTABLES_REMOVE_RULES:
        result = _run(rule, check=False)
        if result.returncode == 0:
            print(f"[defense]   Rule removed: {' '.join(rule[3:])}")
        else:
            print(f"[defense]   Rule not present (skipping).")

    _apache_reload()
    print("[defense] ── Mitigations removed — baseline restored ─────────\n")


# ══════════════════════════════════════════════════════════════
#  STATUS
# ══════════════════════════════════════════════════════════════

def status() -> dict:
    """Print and return current mitigation status."""
    s: dict = {}

    # Apache config
    conf_present = os.path.exists(APACHE_CONF_PATH)
    conf_linked  = os.path.exists(APACHE_CONF_LINK)
    s["apache_conf_present"] = conf_present
    s["apache_conf_enabled"] = conf_linked

    # mod_reqtimeout
    s["mod_reqtimeout_loaded"] = _mod_reqtimeout_enabled()

    # iptables connlimit rule
    result = subprocess.run(
        ["iptables", "-C", "INPUT",
         "-i", IFACE, "-p", "tcp", "--dport", "80",
         "--syn", "-m", "connlimit",
         "--connlimit-above", str(CONNLIMIT_ABOVE),
         "-j", "REJECT", "--reject-with", "tcp-reset"],
        capture_output=True,
    )
    s["connlimit_rule_active"] = (result.returncode == 0)

    # iptables hashlimit rule
    result = subprocess.run(
        ["iptables", "-C", "INPUT",
         "-i", IFACE, "-p", "tcp", "--dport", "80",
         "--syn", "-m", "hashlimit",
         "--hashlimit-name", "slowloris_rl",
         "--hashlimit-above", f"{HASHLIMIT_RATE}/second",
         "--hashlimit-burst", str(HASHLIMIT_BURST),
         "--hashlimit-mode", "srcip",
         "-j", "DROP"],
        capture_output=True,
    )
    s["hashlimit_rule_active"] = (result.returncode == 0)

    all_active = all([
        s["apache_conf_present"],
        s["apache_conf_enabled"],
        s["mod_reqtimeout_loaded"],
        s["connlimit_rule_active"],
        s["hashlimit_rule_active"],
    ])
    s["all_active"] = all_active

    print("\n[defense] ── Mitigation Status ──────────────────────────────")
    rows = [
        ("Apache conf present",      s["apache_conf_present"]),
        ("Apache conf enabled",       s["apache_conf_enabled"]),
        ("mod_reqtimeout loaded",     s["mod_reqtimeout_loaded"]),
        ("connlimit rule (Mitig. 2)", s["connlimit_rule_active"]),
        ("hashlimit rule (Mitig. 4)", s["hashlimit_rule_active"]),
    ]
    for label, val in rows:
        icon = "✓" if val else "✗"
        print(f"  {icon}  {label}")
    print(f"\n  Overall: {'ALL ACTIVE' if all_active else 'PARTIAL / INACTIVE'}")
    print("[defense] ────────────────────────────────────────────────────\n")
    return s


# ══════════════════════════════════════════════════════════════
#  MEASURE  (before/after experiment)
# ══════════════════════════════════════════════════════════════

def measure(c2_ip: str = "192.168.100.10",
            ssh_user: str = "vboxuser",
            num_sockets: int = 150) -> dict:
    """
    Before/after experiment:
      1. Take a baseline connlimit-test snapshot (mitigations OFF).
      2. Enable all mitigations.
      3. Take a post-mitigation connlimit-test snapshot.
      4. Print comparison table and write graph3_slowloris_data.json.

    connlimit-test invokes slowloris.py --connlimit-test on the C2 VM
    (where it is safe to originate attack traffic in the isolated lab).
    """
    _check_root()
    print("\n[defense] ── Before/After Measurement ──────────────────────")

    def _connlimit_snapshot(label: str) -> dict:
        """SSH to C2 VM and run slowloris.py --connlimit-test."""
        print(f"\n[defense] [{label}] Running connlimit-test from C2 VM ({c2_ip})...")
        cmd = [
            "ssh",
            "-o", "StrictHostKeyChecking=no",
            "-o", "ConnectTimeout=5",
            f"{ssh_user}@{c2_ip}",
            f"cd ~/lab && python3 slowloris.py "
            f"--connlimit-test --sockets {num_sockets} "
            f"192.168.100.20 2>/dev/null",
        ]
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=30,
        )

        # Parse the [SLOWLORIS_STATS] line from stdout
        for line in result.stdout.splitlines():
            if line.startswith("[SLOWLORIS_STATS]"):
                try:
                    data = json.loads(line[len("[SLOWLORIS_STATS] "):])
                    data["label"] = label
                    print(f"[defense]   Succeeded: {data['succeeded']}/{data['attempted']} "
                          f"({data['pct_open']}%)")
                    return data
                except (json.JSONDecodeError, KeyError):
                    pass

        # Fallback: couldn't parse
        print(f"[defense]   WARNING: could not parse connlimit-test output.")
        print(f"[defense]   stdout: {result.stdout[:200]}")
        return {"label": label, "succeeded": -1, "attempted": num_sockets,
                "pct_open": -1.0, "error": "parse_failed"}

    # ── Step 1: baseline (mitigations OFF) ────────────────────
    # Ensure mitigations are off for a clean baseline
    disable()
    time.sleep(2)
    before = _connlimit_snapshot("BEFORE mitigation")

    # ── Step 2: enable mitigations ────────────────────────────
    enable()
    time.sleep(3)   # give Apache time to fully reload

    # ── Step 3: post-mitigation snapshot ──────────────────────
    after = _connlimit_snapshot("AFTER mitigation")

    # ── Step 4: comparison table ───────────────────────────────
    b_suc = before.get("succeeded", 0)
    a_suc = after.get("succeeded",  0)
    if b_suc > 0:
        reduction_pct = max(0.0, (b_suc - a_suc) / b_suc * 100)
    else:
        reduction_pct = 0.0

    print("\n[defense] ── Comparison Table ───────────────────────────────")
    print(f"  {'Metric':<30} {'Before':>10} {'After':>10}")
    print(f"  {'─'*30} {'─'*10} {'─'*10}")
    print(f"  {'Sockets attempted':<30} {before['attempted']:>10} {after['attempted']:>10}")
    print(f"  {'Sockets succeeded':<30} {b_suc:>10} {a_suc:>10}")
    print(f"  {'Success %':<30} {before.get('pct_open', -1):>9.1f}% "
          f"{after.get('pct_open', -1):>9.1f}%")
    print(f"\n  Mitigation factor: {reduction_pct:.1f}% reduction in reachable sockets")
    print("[defense] ────────────────────────────────────────────────────")

    # ── Step 5: write graph data ───────────────────────────────
    output = {
        "timestamp":       datetime.now().isoformat(),
        "before":          before,
        "after":           after,
        "reduction_pct":   round(reduction_pct, 1),
        "mitigations": {
            "reqtimeout_header_min_sec":  REQ_TIMEOUT_HEADER_MIN,
            "reqtimeout_header_max_sec":  REQ_TIMEOUT_HEADER_MAX,
            "reqtimeout_minrate_bps":     REQ_TIMEOUT_MINRATE,
            "connlimit_per_ip":           CONNLIMIT_ABOVE,
            "hashlimit_new_syn_per_sec":  HASHLIMIT_RATE,
        },
    }
    out_path = "graph3_slowloris_data.json"
    with open(out_path, "w") as f:
        json.dump(output, f, indent=2)
    print(f"\n[defense] Data saved: {out_path}")
    print("[defense] Run: python3 generate_graphs.py to include in Graph 3\n")
    return output


# ══════════════════════════════════════════════════════════════
#  CLI
# ══════════════════════════════════════════════════════════════

def main() -> None:
    p = argparse.ArgumentParser(
        description="Slowloris mitigation demonstrator — AUA CS 232/337"
    )
    grp = p.add_mutually_exclusive_group(required=True)
    grp.add_argument(
        "--enable",  action="store_true",
        help="Apply all six article mitigations (mod_reqtimeout + iptables)",
    )
    grp.add_argument(
        "--disable", action="store_true",
        help="Remove all mitigations and restore the clean-room baseline",
    )
    grp.add_argument(
        "--status",  action="store_true",
        help="Report which mitigations are currently active",
    )
    grp.add_argument(
        "--measure", action="store_true",
        help=(
            "Run a full before→enable→after experiment and write "
            "graph3_slowloris_data.json"
        ),
    )
    p.add_argument(
        "--c2-ip", default="192.168.100.10",
        help="IP of the C2 VM (for SSH connlimit-test) (default: 192.168.100.10)",
    )
    p.add_argument(
        "--sockets", type=int, default=150,
        help="Socket count for connlimit-test (default: 150)",
    )
    args = p.parse_args()

    if args.enable:
        enable()
    elif args.disable:
        disable()
    elif args.status:
        status()
    elif args.measure:
        measure(c2_ip=args.c2_ip, num_sockets=args.sockets)


if __name__ == "__main__":
    main()
