"""
====================================================
 AUA CS 232/337 - Botnet Research Project
 Component: TLS JA3 Fingerprinting (IDS Engine 7)
 Environment: ISOLATED VM LAB ONLY
====================================================

Implements JA3 fingerprint extraction from raw TLS ClientHello
packets captured by Scapy.  Adds Engine 7 to ids_detector.py.

JA3 = MD5(SSLVersion,Ciphers,Extensions,EllipticCurves,EllipticCurvePointFormats)
Reference: https://github.com/salesforce/ja3

Article mapping (Castle credential stuffing blog):
  "Uniform TLS or header signatures: unusual spikes linked to
   specific TLS fingerprints across login attempts may indicate
   a shared bot framework."
  "Session linking: by linking sessions over time using TLS
   fingerprints and device traits..."

Why TLS fingerprinting catches what HTTP headers cannot:
  A bot can rotate User-Agent, Accept, and other HTTP headers easily.
  The TLS ClientHello is generated by the HTTP library (urllib, requests,
  curl, Go's net/http) BEFORE the application layer and cannot be faked
  without patching the TLS stack.  Two bots running the same version of
  the same library will produce identical JA3 hashes regardless of what
  User-Agent they claim.

  Engine 6 (HTTP fingerprint) catches bots that forget to rotate headers.
  Engine 7 (JA3) catches bots that rotate headers but share a TLS stack —
  the much harder evasion to achieve.

Lab setup:
  - Run fake_portal.py with HTTPS enabled (see --tls flag added by portal patch)
  - Engine 7 sniffs TLS ClientHellos on any TCP port
  - Both bot→portal and bot→C2 TLS connections are fingerprinted

Known JA3 hashes (subset):
  Python urllib/http.client  : 3b5074b1b5d032e5620f69f9159c1db5  (varies by version)
  Python requests + urllib3  : 6734f37431670b3ab4292b8f60f29984
  curl (libcurl)             : cd08e31494f9531f560d64c695473da9
  Go net/http                : b32309a26951912be7dba376398abc3b
  Node.js http(s)            : 37f463bf4616ecd445d4a1937da06e19
  Firefox (latest)           : 579ccef312d18482fc42e2b822ca2430
  Chrome (latest)            : 773906b0efdefa24a7f2b8eb6985bf42
  Headless Chromium (CDP)    : b32309a26951912be7dba376398abc3b  (same as Go!)
  OpenBullet (embedded Chromium): 5353c3cb92f2dcff1a70f8c2481e90db

Usage (standalone):
  from tls_ja3 import extract_ja3, classify_ja3, JA3Tracker
  tracker = JA3Tracker()
  # call tracker.process_packet(pkt) from Scapy sniff callback

Integration with ids_detector.py:
  See ids_detector_patch.py — adds engine7_process(pkt) to packet_handler.
"""

import hashlib
import struct
import time
import threading
from collections import defaultdict
from typing import Optional

try:
    from scapy.all import IP, TCP, Raw
    _SCAPY_OK = True
except ImportError:
    _SCAPY_OK = False

# ── TLS constants ─────────────────────────────────────────────
_TLS_HANDSHAKE  = 0x16
_TLS_CLIENT_HLO = 0x01
_GREASE_TABLE   = {0x0a0a, 0x1a1a, 0x2a2a, 0x3a3a, 0x4a4a,
                   0x5a5a, 0x6a6a, 0x7a7a, 0x8a8a, 0x9a9a,
                   0xaaaa, 0xbaba, 0xcaca, 0xdada, 0xeaea, 0xfafa}

# ── Known-bad JA3 database ────────────────────────────────────
# Maps JA3 hash → {tool, risk, reason}
# Extend this as new hashes are observed in the wild.
KNOWN_BAD_JA3: dict = {
    "3b5074b1b5d032e5620f69f9159c1db5": {
        "tool":   "Python urllib/http.client",
        "risk":   "HIGH",
        "reason": "Python standard library — no browser would produce this hash",
    },
    "6734f37431670b3ab4292b8f60f29984": {
        "tool":   "Python requests + urllib3",
        "risk":   "HIGH",
        "reason": "requests library TLS fingerprint — unambiguously non-browser",
    },
    "cd08e31494f9531f560d64c695473da9": {
        "tool":   "curl (libcurl)",
        "risk":   "HIGH",
        "reason": "curl TLS fingerprint — not a browser",
    },
    "b32309a26951912be7dba376398abc3b": {
        "tool":   "Go net/http OR Headless Chromium (CDP)",
        "risk":   "HIGH",
        "reason": "Go stdlib or headless browser — common bot stack",
    },
    "37f463bf4616ecd445d4a1937da06e19": {
        "tool":   "Node.js https",
        "risk":   "HIGH",
        "reason": "Node.js TLS stack — automation script indicator",
    },
    "5353c3cb92f2dcff1a70f8c2481e90db": {
        "tool":   "OpenBullet / SilverBullet",
        "risk":   "CRITICAL",
        "reason": "OpenBullet embedded Chromium — credential stuffing tool",
    },
    "eb8cff159f8f05b2af530f8cb6a8daf6": {
        "tool":   "Java HttpsURLConnection",
        "risk":   "HIGH",
        "reason": "Java stdlib TLS — not a real browser session",
    },
    "c35abbab7c353ce4f4a9cee6b1379bde": {
        "tool":   "Python aiohttp",
        "risk":   "HIGH",
        "reason": "aiohttp async HTTP client — automation indicator",
    },
}

# ── Known-good JA3 database ───────────────────────────────────
KNOWN_GOOD_JA3: dict = {
    "579ccef312d18482fc42e2b822ca2430": {"browser": "Firefox", "risk": "LOW"},
    "773906b0efdefa24a7f2b8eb6985bf42": {"browser": "Chrome",  "risk": "LOW"},
    "8a8a8a8a8a8a8a8a8a8a8a8a8a8a8a8a": {"browser": "Safari",  "risk": "LOW"},
}


# ── TLS ClientHello parser ────────────────────────────────────

def _parse_client_hello(data: bytes) -> Optional[dict]:
    """
    Parse a raw TLS record containing a ClientHello.

    Returns dict with:
      ssl_version, cipher_suites, extensions,
      elliptic_curves, ec_point_formats
    or None on parse failure.
    """
    try:
        if len(data) < 6:
            return None
        # TLS record header
        if data[0] != _TLS_HANDSHAKE:
            return None
        rec_len = struct.unpack("!H", data[3:5])[0]
        # Handshake header
        hs = data[5:]
        if len(hs) < 4 or hs[0] != _TLS_CLIENT_HLO:
            return None
        hs_len = struct.unpack("!I", b"\x00" + hs[1:4])[0]
        hs = hs[4:4 + hs_len]

        # ClientHello body
        pos = 0
        if len(hs) < 34:
            return None
        ssl_version = struct.unpack("!H", hs[pos:pos+2])[0]
        pos += 2 + 32  # version + random

        # Session ID
        sid_len = hs[pos]; pos += 1 + sid_len

        # Cipher suites
        cs_len = struct.unpack("!H", hs[pos:pos+2])[0]
        pos += 2
        ciphers = []
        for i in range(0, cs_len, 2):
            c = struct.unpack("!H", hs[pos+i:pos+i+2])[0]
            if c not in _GREASE_TABLE:
                ciphers.append(c)
        pos += cs_len

        # Compression methods
        cm_len = hs[pos]; pos += 1 + cm_len

        extensions = []
        elliptic_curves = []
        ec_point_formats = []

        if pos + 2 <= len(hs):
            ext_total = struct.unpack("!H", hs[pos:pos+2])[0]
            pos += 2
            ext_end = pos + ext_total
            while pos + 4 <= ext_end:
                ext_type = struct.unpack("!H", hs[pos:pos+2])[0]
                ext_len  = struct.unpack("!H", hs[pos+2:pos+4])[0]
                ext_data = hs[pos+4:pos+4+ext_len]
                pos += 4 + ext_len
                if ext_type not in _GREASE_TABLE:
                    extensions.append(ext_type)
                # Supported groups (elliptic curves) — type 10
                if ext_type == 10 and len(ext_data) >= 2:
                    gc_len = struct.unpack("!H", ext_data[:2])[0]
                    for i in range(0, gc_len, 2):
                        c = struct.unpack("!H", ext_data[2+i:2+i+2])[0]
                        if c not in _GREASE_TABLE:
                            elliptic_curves.append(c)
                # EC point formats — type 11
                if ext_type == 11 and len(ext_data) >= 1:
                    pf_len = ext_data[0]
                    for i in range(pf_len):
                        ec_point_formats.append(ext_data[1+i])

        return dict(
            ssl_version      = ssl_version,
            cipher_suites    = ciphers,
            extensions       = extensions,
            elliptic_curves  = elliptic_curves,
            ec_point_formats = ec_point_formats,
        )
    except Exception:
        return None


def compute_ja3(parsed: dict) -> str:
    """
    Compute JA3 hash from parsed ClientHello fields.
    JA3 = MD5(SSLVer,Ciphers,Extensions,EllCurves,EllCurvePointFmts)
    """
    def _join(lst):
        return "-".join(str(x) for x in lst)

    ja3_str = ",".join([
        str(parsed["ssl_version"]),
        _join(parsed["cipher_suites"]),
        _join(parsed["extensions"]),
        _join(parsed["elliptic_curves"]),
        _join(parsed["ec_point_formats"]),
    ])
    return hashlib.md5(ja3_str.encode()).hexdigest(), ja3_str


def extract_ja3(pkt) -> Optional[dict]:
    """
    Extract JA3 fingerprint from a Scapy packet.

    Returns dict: {src_ip, dst_ip, dst_port, ja3_hash, ja3_str, parsed}
    or None if not a TLS ClientHello.
    """
    if not _SCAPY_OK:
        return None
    if not (pkt.haslayer(IP) and pkt.haslayer(TCP) and pkt.haslayer(Raw)):
        return None
    raw = bytes(pkt[Raw].load)
    parsed = _parse_client_hello(raw)
    if not parsed:
        return None
    ja3_hash, ja3_str = compute_ja3(parsed)
    return dict(
        src_ip   = pkt[IP].src,
        dst_ip   = pkt[IP].dst,
        dst_port = pkt[TCP].dport,
        ja3_hash = ja3_hash,
        ja3_str  = ja3_str,
        parsed   = parsed,
    )


def classify_ja3(ja3_hash: str) -> dict:
    """
    Classify a JA3 hash as known-bad, known-good, or unknown.
    Returns {classification, tool/browser, risk, reason}.
    """
    if ja3_hash in KNOWN_BAD_JA3:
        info = KNOWN_BAD_JA3[ja3_hash]
        return dict(classification="KNOWN_BAD", **info)
    if ja3_hash in KNOWN_GOOD_JA3:
        info = KNOWN_GOOD_JA3[ja3_hash]
        return dict(classification="KNOWN_GOOD", **info)
    return dict(classification="UNKNOWN", risk="MED",
                reason="Unseen TLS fingerprint — may be rare browser or custom client")


# ── Multi-IP JA3 tracker ──────────────────────────────────────

class JA3Tracker:
    """
    Tracks JA3 hashes across source IPs.

    Two alert classes:
      1. KNOWN_BAD  — a hash in KNOWN_BAD_JA3 seen from any IP
      2. MULTI_IP   — same hash seen from N distinct IPs in WINDOW
                      (identical to Engine 6's HTTP fingerprint logic
                       but at TLS layer — cannot be evaded by header rotation)
    """

    def __init__(self,
                 multiip_min: int = 3,
                 window_sec: float = 300.0):
        self.multiip_min = multiip_min
        self.window_sec  = window_sec
        self._lock = threading.Lock()
        # ja3_hash → list of (timestamp, src_ip)
        self._seen: dict = defaultdict(list)
        self._alerted_bad:    set = set()
        self._alerted_multiip: set = set()

    def process_packet(self, pkt) -> Optional[dict]:
        """
        Process one Scapy packet.  Returns an alert dict or None.
        """
        info = extract_ja3(pkt)
        if not info:
            return None

        ja3  = info["ja3_hash"]
        src  = info["src_ip"]
        now  = time.time()

        classification = classify_ja3(ja3)

        with self._lock:
            self._seen[ja3].append((now, src))
            # prune old entries
            cutoff = now - self.window_sec
            self._seen[ja3] = [(ts, ip) for ts, ip in self._seen[ja3]
                               if ts > cutoff]

            recent = self._seen[ja3]
            distinct_ips = {ip for _, ip in recent}

            # Alert class 1: known-bad tool
            if (classification["classification"] == "KNOWN_BAD"
                    and ja3 not in self._alerted_bad):
                self._alerted_bad.add(ja3)
                return dict(
                    alert_type  = "JA3/KnownBad",
                    severity    = classification["risk"],
                    ja3_hash    = ja3,
                    src_ip      = src,
                    dst_port    = info["dst_port"],
                    tool        = classification.get("tool", "?"),
                    reason      = classification["reason"],
                    message     = (
                        f"KNOWN-BAD JA3 fingerprint detected\n"
                        f"  Hash:    {ja3}\n"
                        f"  Tool:    {classification.get('tool','?')}\n"
                        f"  Src:     {src} → port {info['dst_port']}\n"
                        f"  Reason:  {classification['reason']}\n"
                        f"  MITRE:   T1110.004 (Credential Stuffing)\n"
                        f"  Unlike User-Agent, TLS fingerprint cannot be changed\n"
                        f"  without patching the HTTP library."
                    ),
                )

            # Alert class 2: same fingerprint across many IPs
            if (len(distinct_ips) >= self.multiip_min
                    and ja3 not in self._alerted_multiip):
                self._alerted_multiip.add(ja3)
                return dict(
                    alert_type   = "JA3/MultiIP",
                    severity     = "HIGH",
                    ja3_hash     = ja3,
                    n_ips        = len(distinct_ips),
                    ips          = list(distinct_ips),
                    classification = classification["classification"],
                    message      = (
                        f"DISTRIBUTED TLS FINGERPRINT detected\n"
                        f"  Hash:       {ja3}\n"
                        f"  Seen from:  {len(distinct_ips)} distinct source IPs\n"
                        f"    {list(distinct_ips)}\n"
                        f"  Window:     {self.window_sec:.0f}s\n"
                        f"  Tool guess: {classification.get('tool', classification.get('browser','unknown'))}\n"
                        f"  Identical TLS stack across IPs → same bot framework\n"
                        f"  This attack evades HTTP header rotation (Engine 6)\n"
                        f"  because TLS fingerprint is library-level, not app-level.\n"
                        f"  MITRE: T1090 (Proxy) + T1110.004 (Credential Stuffing)"
                    ),
                )
        return None

    def get_stats(self) -> dict:
        """Return current tracker state for status/debug."""
        with self._lock:
            now = time.time()
            cutoff = now - self.window_sec
            active = {}
            for ja3, entries in self._seen.items():
                recent = [(ts, ip) for ts, ip in entries if ts > cutoff]
                if recent:
                    active[ja3] = {
                        "n_ips": len({ip for _, ip in recent}),
                        "ips":   list({ip for _, ip in recent}),
                        "classification": classify_ja3(ja3)["classification"],
                    }
            return active


# ── Singleton tracker for integration with ids_detector.py ───
_tracker = JA3Tracker()


def engine7_process(pkt) -> Optional[dict]:
    """Drop-in call from ids_detector.packet_handler()."""
    return _tracker.process_packet(pkt)


def get_tracker_stats() -> dict:
    return _tracker.get_stats()


if __name__ == "__main__":
    print("JA3 module loaded.  Known-bad entries:", len(KNOWN_BAD_JA3))
    print("Run ids_detector.py to activate Engine 7 packet sniffing.")
    print()
    for h, info in list(KNOWN_BAD_JA3.items())[:5]:
        print(f"  {h[:16]}…  {info['tool']}")
